-- =====================================================================================
-- Grossimarché — initial schema (V1)
-- Flyway is the sole owner of the schema; Hibernate runs in validate mode.
-- Money: NUMERIC(12,2). Quantities: integer. Timestamps: timestamptz (UTC).
-- Primary keys are UUID v7, generated by the application (time-ordered → good locality).
-- =====================================================================================

-- Accent-insensitive French full-text search needs an IMMUTABLE unaccent wrapper so it
-- can be used in a generated column / functional index (plain unaccent() is only STABLE).
CREATE EXTENSION IF NOT EXISTS unaccent;

CREATE OR REPLACE FUNCTION f_unaccent(text) RETURNS text
    LANGUAGE sql IMMUTABLE PARALLEL SAFE STRICT AS
$$
SELECT unaccent('unaccent', $1)
$$;

-- ---------------------------------------------------------------------------
-- Users & addresses
-- ---------------------------------------------------------------------------
CREATE TABLE users
(
    id              UUID PRIMARY KEY,
    full_name       VARCHAR(150),
    phone           VARCHAR(20) UNIQUE,
    email           VARCHAR(255) UNIQUE,
    role            VARCHAR(20)  NOT NULL,
    status          VARCHAR(20)  NOT NULL,
    phone_verified  BOOLEAN      NOT NULL DEFAULT FALSE,
    email_verified  BOOLEAN      NOT NULL DEFAULT FALSE,
    consent_at      TIMESTAMPTZ,
    consent_version VARCHAR(20),
    last_login_at   TIMESTAMPTZ,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT ck_users_phone_or_email CHECK (phone IS NOT NULL OR email IS NOT NULL)
);

CREATE TABLE addresses
(
    id           UUID PRIMARY KEY,
    user_id      UUID         NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    label        VARCHAR(60),
    city         VARCHAR(100) NOT NULL,
    address_line VARCHAR(255) NOT NULL,
    lat          DOUBLE PRECISION,
    lng          DOUBLE PRECISION,
    is_default   BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- At most one default address per user.
CREATE UNIQUE INDEX ux_addresses_one_default_per_user
    ON addresses (user_id) WHERE is_default;
CREATE INDEX ix_addresses_user ON addresses (user_id);

-- ---------------------------------------------------------------------------
-- Catalogue
-- ---------------------------------------------------------------------------
CREATE TABLE categories
(
    id            UUID PRIMARY KEY,
    name          VARCHAR(100) NOT NULL,
    slug          VARCHAR(120) NOT NULL UNIQUE,
    icon          VARCHAR(60),
    display_order INTEGER      NOT NULL DEFAULT 0,
    active        BOOLEAN      NOT NULL DEFAULT TRUE
);

CREATE TABLE products
(
    id                 UUID PRIMARY KEY,
    category_id        UUID           NOT NULL REFERENCES categories (id),
    name               VARCHAR(200)   NOT NULL,
    slug               VARCHAR(220)   NOT NULL UNIQUE,
    description        TEXT,
    price              NUMERIC(12, 2) NOT NULL,
    unit               VARCHAR(40)    NOT NULL,
    stock_quantity     INTEGER        NOT NULL DEFAULT 0,
    min_order_quantity INTEGER        NOT NULL DEFAULT 1,
    image_url          VARCHAR(500),
    active             BOOLEAN        NOT NULL DEFAULT TRUE,
    version            BIGINT         NOT NULL DEFAULT 0,
    created_at         TIMESTAMPTZ    NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ    NOT NULL DEFAULT now(),
    -- Accent-insensitive French search vector over name + description.
    search_vector      tsvector GENERATED ALWAYS AS (
                           to_tsvector('french',
                               f_unaccent(coalesce(name, '') || ' ' || coalesce(description, '')))
                           ) STORED
);

CREATE INDEX ix_products_category_active ON products (category_id, active);
CREATE INDEX ix_products_search ON products USING GIN (search_vector);

CREATE TABLE product_price_tiers
(
    id           UUID PRIMARY KEY,
    product_id   UUID           NOT NULL REFERENCES products (id) ON DELETE CASCADE,
    min_quantity INTEGER        NOT NULL,
    unit_price   NUMERIC(12, 2) NOT NULL,
    CONSTRAINT uq_price_tier UNIQUE (product_id, min_quantity)
);
CREATE INDEX ix_price_tiers_product ON product_price_tiers (product_id);

-- ---------------------------------------------------------------------------
-- Cart
-- ---------------------------------------------------------------------------
CREATE TABLE carts
(
    id         UUID PRIMARY KEY,
    user_id    UUID        NOT NULL UNIQUE REFERENCES users (id) ON DELETE CASCADE,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE cart_items
(
    id         UUID PRIMARY KEY,
    cart_id    UUID    NOT NULL REFERENCES carts (id) ON DELETE CASCADE,
    product_id UUID    NOT NULL REFERENCES products (id),
    quantity   INTEGER NOT NULL,
    CONSTRAINT uq_cart_item UNIQUE (cart_id, product_id)
);
CREATE INDEX ix_cart_items_cart ON cart_items (cart_id);

-- ---------------------------------------------------------------------------
-- Orders
-- ---------------------------------------------------------------------------
CREATE TABLE orders
(
    id               UUID PRIMARY KEY,
    order_number     VARCHAR(30)    NOT NULL UNIQUE,
    user_id          UUID           NOT NULL REFERENCES users (id),
    address_snapshot JSONB          NOT NULL,
    status           VARCHAR(20)    NOT NULL,
    payment_method   VARCHAR(10)    NOT NULL,
    payment_status   VARCHAR(20)    NOT NULL,
    subtotal         NUMERIC(12, 2) NOT NULL,
    discount_total   NUMERIC(12, 2) NOT NULL DEFAULT 0,
    delivery_fee     NUMERIC(12, 2) NOT NULL DEFAULT 0,
    total            NUMERIC(12, 2) NOT NULL,
    note             VARCHAR(500),
    idempotency_key  VARCHAR(100)   NOT NULL UNIQUE,
    version          BIGINT         NOT NULL DEFAULT 0,
    created_at       TIMESTAMPTZ    NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ    NOT NULL DEFAULT now()
);
CREATE INDEX ix_orders_user_created ON orders (user_id, created_at DESC);
CREATE INDEX ix_orders_status_created ON orders (status, created_at DESC);

CREATE TABLE order_items
(
    id                    UUID PRIMARY KEY,
    order_id              UUID           NOT NULL REFERENCES orders (id) ON DELETE CASCADE,
    product_id            UUID           NOT NULL REFERENCES products (id),
    product_name_snapshot VARCHAR(200)   NOT NULL,
    unit_snapshot         VARCHAR(40)    NOT NULL,
    quantity              INTEGER        NOT NULL,
    unit_price            NUMERIC(12, 2) NOT NULL,
    line_total            NUMERIC(12, 2) NOT NULL
);
CREATE INDEX ix_order_items_order ON order_items (order_id);

CREATE TABLE order_status_history
(
    id         UUID PRIMARY KEY,
    order_id   UUID        NOT NULL REFERENCES orders (id) ON DELETE CASCADE,
    status     VARCHAR(20) NOT NULL,
    changed_by UUID,
    note       VARCHAR(255),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX ix_order_status_history_order ON order_status_history (order_id, created_at);

-- ---------------------------------------------------------------------------
-- Loyalty
-- ---------------------------------------------------------------------------
CREATE TABLE loyalty_accounts
(
    user_id        UUID PRIMARY KEY REFERENCES users (id) ON DELETE CASCADE,
    points_balance INTEGER     NOT NULL DEFAULT 0,
    lifetime_points INTEGER    NOT NULL DEFAULT 0,
    tier           VARCHAR(20) NOT NULL DEFAULT 'BRONZE',
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE loyalty_transactions
(
    id         UUID PRIMARY KEY,
    user_id    UUID        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    points     INTEGER     NOT NULL,
    type       VARCHAR(20) NOT NULL,
    order_id   UUID        REFERENCES orders (id) ON DELETE SET NULL,
    note       VARCHAR(255),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX ix_loyalty_tx_user_created ON loyalty_transactions (user_id, created_at DESC);

-- ---------------------------------------------------------------------------
-- Stores
-- ---------------------------------------------------------------------------
CREATE TABLE stores
(
    id            UUID PRIMARY KEY,
    name          VARCHAR(150)     NOT NULL,
    city          VARCHAR(100)     NOT NULL,
    address       VARCHAR(255)     NOT NULL,
    phone         VARCHAR(20),
    opening_hours JSONB,
    lat           DOUBLE PRECISION NOT NULL,
    lng           DOUBLE PRECISION NOT NULL,
    active        BOOLEAN          NOT NULL DEFAULT TRUE
);
CREATE INDEX ix_stores_lat_lng ON stores (lat, lng);

-- ---------------------------------------------------------------------------
-- Audit
-- ---------------------------------------------------------------------------
CREATE TABLE audit_logs
(
    id          UUID PRIMARY KEY,
    actor_id    UUID,
    action      VARCHAR(80)  NOT NULL,
    entity_type VARCHAR(80),
    entity_id   VARCHAR(80),
    ip          VARCHAR(60),
    user_agent  VARCHAR(400),
    metadata    JSONB,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX ix_audit_logs_created ON audit_logs (created_at DESC);
