-- =====================================================================================
-- Grossimarché — V3: coupons, product attributes, product reviews.
-- Plus the RESERVED variant-SKU schema (empty, unmapped — no entity references it yet),
-- so Phase B can wire variants without another migration. Same conventions as V1:
-- money NUMERIC(12,2); UUID PKs generated by the app; timestamps timestamptz (UTC).
-- Hibernate runs in validate mode, so every mapped entity must match a column here; the
-- reserved tables/columns below are intentionally left unmapped and validate ignores them.
-- =====================================================================================

-- ---------------------------------------------------------------------------
-- Coupons
-- ---------------------------------------------------------------------------
CREATE TABLE coupons
(
    id                 UUID PRIMARY KEY,
    code               VARCHAR(40)    NOT NULL UNIQUE,
    type               VARCHAR(20)    NOT NULL,          -- PERCENTAGE | FIXED
    value              NUMERIC(12, 2) NOT NULL,          -- 10 (=10%) or 50.00 (=50 MAD)
    min_order_subtotal NUMERIC(12, 2) NOT NULL DEFAULT 0,
    max_discount       NUMERIC(12, 2),                   -- cap for percentage; NULL = no cap
    starts_at          TIMESTAMPTZ,
    expires_at         TIMESTAMPTZ,
    usage_limit        INTEGER,                          -- total redemptions; NULL = unlimited
    per_user_limit     INTEGER        NOT NULL DEFAULT 1,
    active             BOOLEAN        NOT NULL DEFAULT TRUE,
    created_at         TIMESTAMPTZ    NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ    NOT NULL DEFAULT now(),
    CONSTRAINT ck_coupon_type CHECK (type IN ('PERCENTAGE', 'FIXED')),
    CONSTRAINT ck_coupon_value_positive CHECK (value > 0)
);

-- One row per successful use — powers usage/per-user limits and cancellation reversal.
CREATE TABLE coupon_redemptions
(
    id              UUID PRIMARY KEY,
    coupon_id       UUID           NOT NULL REFERENCES coupons (id) ON DELETE CASCADE,
    user_id         UUID           NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    order_id        UUID           REFERENCES orders (id) ON DELETE SET NULL,
    discount_amount NUMERIC(12, 2) NOT NULL,
    created_at      TIMESTAMPTZ    NOT NULL DEFAULT now()
);
CREATE INDEX ix_coupon_redemptions_coupon ON coupon_redemptions (coupon_id);
CREATE INDEX ix_coupon_redemptions_coupon_user ON coupon_redemptions (coupon_id, user_id);
-- At most one redemption row per order (idempotent checkout).
CREATE UNIQUE INDEX ux_coupon_redemption_order ON coupon_redemptions (order_id) WHERE order_id IS NOT NULL;

-- Coupon snapshot on the order (frozen like every other order total).
ALTER TABLE orders ADD COLUMN coupon_code     VARCHAR(40);
ALTER TABLE orders ADD COLUMN coupon_discount NUMERIC(12, 2) NOT NULL DEFAULT 0;

-- ---------------------------------------------------------------------------
-- Product attributes (informational key/value: brand, origin, packaging…)
-- ---------------------------------------------------------------------------
CREATE TABLE product_attributes
(
    id            UUID PRIMARY KEY,
    product_id    UUID         NOT NULL REFERENCES products (id) ON DELETE CASCADE,
    name          VARCHAR(80)  NOT NULL,
    value         VARCHAR(255) NOT NULL,
    display_order INTEGER      NOT NULL DEFAULT 0
);
CREATE INDEX ix_product_attributes_product ON product_attributes (product_id, display_order);

-- ---------------------------------------------------------------------------
-- Product reviews (rating 1–5, admin-moderated via `approved`)
-- ---------------------------------------------------------------------------
CREATE TABLE product_reviews
(
    id         UUID PRIMARY KEY,
    product_id UUID          NOT NULL REFERENCES products (id) ON DELETE CASCADE,
    user_id    UUID          NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    rating     INTEGER       NOT NULL,
    comment    VARCHAR(2000),
    approved   BOOLEAN       NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT ck_review_rating CHECK (rating BETWEEN 1 AND 5),
    CONSTRAINT uq_review_user_product UNIQUE (product_id, user_id)
);
CREATE INDEX ix_product_reviews_product ON product_reviews (product_id, approved);

-- =====================================================================================
-- RESERVED — Phase B variant SKUs. Created now (zero-risk) so Phase B needs no migration
-- rewrite. No JPA entity maps these yet; cart/checkout/stock stay product-level for now.
-- =====================================================================================
CREATE TABLE product_variants
(
    id             UUID PRIMARY KEY,
    product_id     UUID          NOT NULL REFERENCES products (id) ON DELETE CASCADE,
    sku            VARCHAR(80)   NOT NULL UNIQUE,
    price          NUMERIC(12, 2),                       -- NULL → falls back to product.price
    stock_quantity INTEGER       NOT NULL DEFAULT 0,
    active         BOOLEAN       NOT NULL DEFAULT TRUE,
    version        BIGINT        NOT NULL DEFAULT 0,
    created_at     TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ   NOT NULL DEFAULT now()
);
CREATE INDEX ix_product_variants_product ON product_variants (product_id, active);

CREATE TABLE variant_option_values
(
    id         UUID PRIMARY KEY,
    variant_id UUID         NOT NULL REFERENCES product_variants (id) ON DELETE CASCADE,
    name       VARCHAR(80)  NOT NULL,                    -- e.g. "Taille"
    value      VARCHAR(120) NOT NULL                     -- e.g. "M"
);
CREATE INDEX ix_variant_option_values_variant ON variant_option_values (variant_id);

-- Reserved nullable links (always NULL until Phase B wires variants into cart/checkout).
ALTER TABLE cart_items  ADD COLUMN variant_id       UUID REFERENCES product_variants (id) ON DELETE CASCADE;
ALTER TABLE order_items ADD COLUMN variant_id       UUID REFERENCES product_variants (id);
ALTER TABLE order_items ADD COLUMN variant_snapshot VARCHAR(255);
