-- =====================================================================================
-- Grossimarché - V5: back-office configuration (currencies, languages, attribute
-- catalogue) and the staff notification feed. Same conventions as V1/V3: UUID PKs
-- generated by the app; money/rates NUMERIC; timestamps timestamptz (UTC). Hibernate runs
-- in validate mode, so every column here must match a mapped entity.
--
-- Reference defaults (MAD currency, fr/ar/en languages) are seeded HERE (not in db/seed)
-- because they are needed in every environment, including production - the storefront reads
-- the active currency/languages from these tables.
-- =====================================================================================

-- ---------------------------------------------------------------------------
-- Currencies (ADMIN-managed configuration). Exactly one row has is_default = true.
-- ---------------------------------------------------------------------------
CREATE TABLE currencies
(
    id            UUID PRIMARY KEY,
    code          VARCHAR(10)    NOT NULL UNIQUE,          -- ISO 4217, e.g. MAD
    name          VARCHAR(60)    NOT NULL,
    symbol        VARCHAR(10)    NOT NULL,
    exchange_rate NUMERIC(18, 6) NOT NULL DEFAULT 1,       -- rate relative to the default currency
    is_default    BOOLEAN        NOT NULL DEFAULT FALSE,
    enabled       BOOLEAN        NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ    NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ    NOT NULL DEFAULT now()
);
-- At most one default currency.
CREATE UNIQUE INDEX ux_currency_default ON currencies (is_default) WHERE is_default = TRUE;

INSERT INTO currencies (id, code, name, symbol, exchange_rate, is_default, enabled)
VALUES
    (gen_random_uuid(), 'MAD', 'Dirham marocain', 'DH', 1.000000, TRUE, TRUE),
    (gen_random_uuid(), 'EUR', 'Euro', '€', 0.093000, FALSE, FALSE),
    (gen_random_uuid(), 'USD', 'Dollar américain', '$', 0.100000, FALSE, FALSE);

-- ---------------------------------------------------------------------------
-- Languages (ADMIN-managed configuration). Exactly one row has is_default = true.
-- ---------------------------------------------------------------------------
CREATE TABLE languages
(
    id         UUID PRIMARY KEY,
    name       VARCHAR(60)  NOT NULL,
    iso_code   VARCHAR(10)  NOT NULL UNIQUE,               -- e.g. fr, ar, en
    flag       VARCHAR(255),
    is_default BOOLEAN      NOT NULL DEFAULT FALSE,
    enabled    BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX ux_language_default ON languages (is_default) WHERE is_default = TRUE;

INSERT INTO languages (id, name, iso_code, flag, is_default, enabled)
VALUES
    (gen_random_uuid(), 'Français', 'fr', '🇫🇷', TRUE, TRUE),
    (gen_random_uuid(), 'العربية', 'ar', '🇲🇦', FALSE, TRUE),
    (gen_random_uuid(), 'English', 'en', '🇬🇧', FALSE, FALSE);

-- ---------------------------------------------------------------------------
-- Attribute catalogue: reusable attribute definitions with their allowed values
-- (e.g. Marque → [Marque A, Marque B], Conditionnement → [Carton, Sachet]).
-- ---------------------------------------------------------------------------
CREATE TABLE attributes
(
    id         UUID PRIMARY KEY,
    name       VARCHAR(80) NOT NULL,
    type       VARCHAR(20) NOT NULL DEFAULT 'OPTION',      -- OPTION | CHECKBOX
    enabled    BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_attribute_type CHECK (type IN ('OPTION', 'CHECKBOX'))
);

CREATE TABLE attribute_values
(
    id            UUID PRIMARY KEY,
    attribute_id  UUID         NOT NULL REFERENCES attributes (id) ON DELETE CASCADE,
    name          VARCHAR(120) NOT NULL,
    enabled       BOOLEAN      NOT NULL DEFAULT TRUE,
    display_order INTEGER      NOT NULL DEFAULT 0
);
CREATE INDEX ix_attribute_values_attribute ON attribute_values (attribute_id, display_order);

-- Two wholesale-relevant sample attributes with values.
INSERT INTO attributes (id, name, type, enabled)
VALUES
    ('11111111-1111-1111-1111-111111111111', 'Marque', 'OPTION', TRUE),
    ('22222222-2222-2222-2222-222222222222', 'Conditionnement', 'OPTION', TRUE);

INSERT INTO attribute_values (id, attribute_id, name, enabled, display_order)
VALUES
    (gen_random_uuid(), '11111111-1111-1111-1111-111111111111', 'Sans marque', TRUE, 0),
    (gen_random_uuid(), '11111111-1111-1111-1111-111111111111', 'Marque distributeur', TRUE, 1),
    (gen_random_uuid(), '22222222-2222-2222-2222-222222222222', 'Carton', TRUE, 0),
    (gen_random_uuid(), '22222222-2222-2222-2222-222222222222', 'Sachet', TRUE, 1),
    (gen_random_uuid(), '22222222-2222-2222-2222-222222222222', 'Palette', TRUE, 2);

-- ---------------------------------------------------------------------------
-- Staff notification feed (NEW_ORDER, LOW_STOCK, …). Read by ADMIN and STORE_MANAGER;
-- also pushed live over STOMP to /topic/admin/notifications.
-- ---------------------------------------------------------------------------
CREATE TABLE notifications
(
    id           UUID PRIMARY KEY,
    type         VARCHAR(20)  NOT NULL,                    -- NEW_ORDER | LOW_STOCK | SYSTEM
    title        VARCHAR(150) NOT NULL,
    message      VARCHAR(500),
    reference_id UUID,                                     -- e.g. order id / product id
    is_read      BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT ck_notification_type CHECK (type IN ('NEW_ORDER', 'LOW_STOCK', 'SYSTEM'))
);
CREATE INDEX ix_notifications_created ON notifications (created_at DESC);
CREATE INDEX ix_notifications_unread ON notifications (is_read) WHERE is_read = FALSE;
