package com.grossimarche.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Id;
import jakarta.persistence.MappedSuperclass;
import org.hibernate.Hibernate;
import org.hibernate.annotations.UuidGenerator;

import java.util.UUID;

/**
 * Root for entities with a surrogate UUID primary key. The id is a time-ordered UUID
 * generated by the application (better B-tree locality than a random v4).
 *
 * <p>{@code equals}/{@code hashCode} are based on the id only and are proxy-safe, so
 * entities behave correctly in collections and across lazy-loading boundaries. Never use
 * Lombok {@code @Data}/{@code @EqualsAndHashCode} on entities.
 */
@MappedSuperclass
public abstract class BaseEntity {

    @Id
    @UuidGenerator(style = UuidGenerator.Style.TIME)
    @Column(name = "id", nullable = false, updatable = false)
    private UUID id;

    public UUID getId() {
        return id;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || Hibernate.getClass(this) != Hibernate.getClass(o)) {
            return false;
        }
        BaseEntity other = (BaseEntity) o;
        return id != null && id.equals(other.id);
    }

    @Override
    public int hashCode() {
        return Hibernate.getClass(this).hashCode();
    }
}
