package com.grossimarche.dto.staff;

import com.grossimarche.entity.enums.Role;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

/**
 * Invite a staff member.
 *
 * The e-mail is required - unlike a customer, a staff account signs in with a password, and
 * that password is generated by the server and delivered to this address. The phone stays
 * optional contact information.
 */
public record CreateStaffRequest(
        @Size(max = 150) String fullName,
        @Size(max = 20) String phone,
        @NotBlank @Email @Size(max = 255) String email,
        @NotNull Role role
) {
}
